version: '3'
services:
    ch-server:
     build: .
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144